### ISSUE TITLE
Moving to the new .NET Foundation CLA service

### ISSUE THREAD

**Issue by ChrisSfanos** [Daniel-Svensson/OpenRiaServices#21]
Hey @Daniel-Svensson - we are moving all .NET Foundation projects to the new CLA service.  Can you drop me a note at chris.sfanos @ dotnetfoundation.org to chat?  We can either do the work for you or provide the steps/etc for you to get it done.  Let me know which you prefer - thanks!

Chris 
DNF Operations team

**Comment by Daniel-Svensson** [comment]
Replied and move is in progress (have a mail discussion)
